version: '3.8'

services:
  backend1:
    build:
      dockerfile: 1.Dockerfile
    container_name: backend1
    ports:
      - "8081:80"

  backend2:
    build:
      dockerfile: 2.Dockerfile
    container_name: backend2
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8091:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf