services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"       # Jenkins 웹 UI 포트
      - "50000:50000"     # Jenkins 에이전트 통신 포트
    volumes:
      - ./jenkins:/var/jenkins_home   # 데이터 영속성을 위해 docker-compose.yml 파일이 있는 곳에 jenkins 설정 파일을 생성한다. 